### ISSUE TITLE
Floating Search Bar misplacement

### ISSUE THREAD

**Issue by NikunjKhangwal** [fast4x/RiMusic#1569]
### Steps to reproduce the bug

Enable Vi Music Mode
Check floating search button position

### Expected behavior

It's appearing in the middle of screen

### Actual behavior

It should appear in bottom right corner and above navigation bar as before

### Screenshots/Screen recordings

![IMG_20240420_072202](https://github.com/fast4x/RiMusic/assets/99175083/6ddeee65-2b85-4937-9a59-ff2ec9b374b9)

### RiMusic version

0.6.31

### Android version

Android 12

**Comment by NikunjKhangwal** [comment]
Same for radio button in artist info and possibly other similar buttons too

**Comment by fast4x** [comment]
Improved, available from version 0.6.32

**Comment by NikunjKhangwal** [comment]
@fast4x Go to top button is still bugged, can you take a look?

![Screenshot_2024-04-28-10-46-38-655_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/99175083/915c3ada-d389-4508-8260-d633d701d4cf)

**Comment by fast4x** [comment]
Yes, it's fixed in 0.6.33

**Comment by NikunjKhangwal** [comment]
@fast4x The icon is too close to the screen edge, can you take a look?

![IMG_20240505_114046](https://github.com/fast4x/RiMusic/assets/99175083/1d56deac-cef2-4024-bb08-61c2103983c1)

**Comment by NikunjKhangwal** [comment]
@fast4x These buttons still appear this way in 0.6.34

![Screenshot_2024-05-11-07-49-53-365_it fast4x rimusic](https://github.com/fast4x/RiMusic/assets/99175083/e92f1254-8808-4910-ae56-81deda3c85f5)
