### ISSUE TITLE
App crashes when there's no internet connection

### ISSUE THREAD

**Issue by Gthbacc** [fast4x/RiMusic#164]
This issue wasnt present before adding the download feature. 
Also if it helps: when there is an internet connection, as soon as the app opens, the download notification pops up, stays for 5 seconds and then closes.
Thanks for maintaining the app btw.

**Comment by fast4x** [comment]
Any questions, if no internet connection.
does it crash when you open the app or play a song?
If you close and reopen the app, is the download successful or not?

**Comment by fast4x** [comment]
I'll add a internet connection checker, thanks for feedback

**Comment by Gthbacc** [comment]
> Any questions, if no internet connection.
> does it crash when you open the app or play a song?
> If you close and reopen the app, is the download successful or not?

It immediately crashed upon opening the app. Also as Snyret mentioned, it's probably just scanning for a download. There's no indication whether the download is successful or not.

**Comment by fast4x** [comment]
Your Android version?
In the next release, I will insert a different function to check the status of the internet connection, should solve the problem.

**Comment by Gthbacc** [comment]
> Your Android version?
11. Thanks for your work.

**Comment by Gthbacc** [comment]
Hey. Thought I should inform you that both issues mentioned in this thread still exist in the new update as well. Even uninstalled the app and re-installed it again. Not sure what the issue is. Thanks.

**Comment by eerqx** [comment]
****

> Fixed, available from version 0.6.12 I think I figured it out, if he shows up again, let me know.

It's not fixed in this update also and the changelog also not mentions it.

**Comment by fast4x** [comment]
ok I check better, thanks

**Comment by fast4x** [comment]
Can you tell me more about the error?
The thing is very strange

**Comment by fast4x** [comment]
> ****
> 
> > Fixed, available from version 0.6.12 I think I figured it out, if he shows up again, let me know.
> 
> It's not fixed in this update also and the changelog also not mentions it.

It is mentioned in What's Changed

**Comment by fast4x** [comment]
> ****
> 
> > Fixed, available from version 0.6.12 I think I figured it out, if he shows up again, let me know.
> 
> It's not fixed in this update also and the changelog also not mentions it.

Does your device have Android 11?

**Comment by Gthbacc** [comment]
> Can you tell me more about the error?
> The thing is very strange
Honestly not much to say. I think it started happening after the app became capable of playing local files. Maybe it had sth to do with that?

**Comment by fast4x** [comment]
Okay, I think I found the problem on Android 11, maybe even on the 10. I’ll do a test.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.13

**Comment by eerqx** [comment]
> > > Fixed, available from version 0.6.12 I think I figured it out, if he shows up again, let me know.
> > 
> > 
> > It's not fixed in this update also and the changelog also not mentions it.
> 
> Does your device have Android 11?

A10
