### ISSUE TITLE
Scrolling in queue that song got disappeared

### ISSUE THREAD

**Issue by Gauravchaubey66** [fast4x/RiMusic#1817]
### Steps to reproduce the bug

1. Play any music 
2. Go to queue
3. Scroll down or up any song

Uploading Project_05-10_SD 360p_MEDIUM_FR30.mp4…

### Expected behavior

"That should not disappeared"

### Actual behavior

"Got disappeared"

### RiMusic version

0.6.33

### Android version

Android 13

**Comment by Gauravchaubey66** [comment]
https://github.com/fast4x/RiMusic/assets/149640114/cdf1cbb9-c631-4d4c-8332-33ec330a31c4

**Comment by Gauravchaubey66** [comment]
This  bug is still there #@fast4x

**Comment by Gauravchaubey66** [comment]
@fast4x its still there I think you don't have time to check this ok I hope you will notice it.
https://github.com/fast4x/RiMusic/assets/149640114/d56c65ff-d1e2-4988-957c-889b2cbd5c03

**Comment by fast4x** [comment]
Fixed, available from version 0.6.38

**Comment by Gauravchaubey66** [comment]
> Fixed, available from version 0.6.38

But it's not fixed ye @fast4x I am attaching a screen recording.
