### ISSUE TITLE
Problems with the "Add to playlist" function

### ISSUE THREAD

**Issue by DollynDeveloper** [fast4x/RiMusic#2565]
### Steps to reproduce the bug

In short: when trying to add a community playlist to another playlist, a pop-up appears on the screen saying "Finish", however, nothing happens; The songs are simply not added to the device's local playlist.  

### Expected behavior

That the playlist is added to the one that is locally stored. 

### Actual behavior

Anything. None of the songs are added to the local playlist. 

### RiMusic version

0.6.41

### Android version

Android 11

**Comment by fast4x** [comment]
Fixed, available from version 0.6.44

**Comment by DollynDeveloper** [comment]
After the update, it still doesn't work. Now the problem is: within a playlist, when clicking the "add to playlist" button, nothing simply appears on the screen.

**Comment by fast4x** [comment]
Add video please
