### ISSUE TITLE
Player minimizing when skipping to next song in the new modern player type in the latest update

### ISSUE THREAD

**Issue by RevanthSurapaneni** [fast4x/RiMusic#2965]
### Steps to reproduce the bug

1. Go to player appearance in  settings and change player type to modern
2. Go to a playlist and start it
3. Go to full player 
4. Press the skip to next song button

### Expected behavior

Skip to next song without minimizing the player

### Actual behavior

Skips to next song, but minimizes the player

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/09943441-4c70-4b46-be58-ac72648db08b

### RiMusic version

0.6.45

### Android version

Android 13

### Additional information

I'm not sure why it happens... just wanted to use carousel

**Comment by aneesh1122** [comment]
Uninstall the app and install it again

**Comment by RevanthSurapaneni** [comment]
didn't work :( i uninstalled it and installed 0.6.45 and then i uninstalled and installed the newer version. still the same issue.

**Comment by aneesh1122** [comment]
@ALMIGHTY-VC help him

**Comment by ALMIGHTY-VC** [comment]
> @ALMIGHTY-VC help him

Bruh in my case the app was closing when i was changing songs in carousel view for him its changing by playback buttons but the problem is never encountered an issue with the playback buttons😵👾

**Comment by ALMIGHTY-VC** [comment]
For him i tried to reproduce the bugs i got the same issue too on my all songs(tab) and liked songs but when i restarted my apps everything was working functionally including playing songs in a playlist
P. S sometimes i do get it while swiping songs in carousel view but i think its because i swipe my player too with the songs

**Comment by ALMIGHTY-VC** [comment]
> ### Steps to reproduce the bug
> 1. Go to player appearance in  settings and change player type to modern
> 2. Go to a playlist and start it
> 3. Go to full player
> 4. Press the skip to next song button
> 
> ### Expected behavior
> Skip to next song without minimizing the player
> 
> ### Actual behavior
> Skips to next song, but minimizes the player
> 
> ### Screenshots/Screen recordings
>  Screen_Recording_20240727_232009.mp4 
> ### Logs
> _No response_
> 
> ### RiMusic version
> 0.6.45
> 
> ### Android version
> Android 13
> 
> ### Additional information
> I'm not sure why it happens... just wanted to use carousel

Does it happen when you freshly start the app or move to it from any other app while it is opened in the background because i encountered such situations when i was opening ri from background and playing music but it got solved by itself and i didn't had to do anything

**Comment by RevanthSurapaneni** [comment]
> Does it happen when you freshly start the app or move to it from any other app while it is opened in the background because i encountered such situations when i was opening ri from background and playing music but it got solved by itself and i didn't had to do anything

tried both scenarios right now, happens in both of them. 

something to note... when i skip to next song, it starts playing for a split second, then the player minimized and the song starts over again

**Comment by aneesh1122** [comment]
> 
> > Does it happen when you freshly start the app or move to it from any other app while it is opened in the background because i encountered such situations when i was opening ri from background and playing music but it got solved by itself and i didn't had to do anything
> 
> tried both scenarios right now, happens in both of them. 
> 
> something to note... when i skip to next song, it starts playing for a split second, then the player minimized and the song starts over again

Try the next version. I've fixed some of the bugs.

I had this player minimizing problem in my PC too using the windows subsystem but it got solved as I was changing codes.

**Comment by aneesh1122** [comment]
install this and see if you are still having this problem

https://github.com/fast4x/RiMusic/tree/master/customVersion

**Comment by RevanthSurapaneni** [comment]
> install this and see if you are still having this problem
> 
> https://github.com/fast4x/RiMusic/tree/master/customVersion

I installed it. I no longer have the problem with the playback buttons.  But it still happens when I use the carousel

**Comment by aneesh1122** [comment]
> > install this and see if you are still having this problem
> > 
> > https://github.com/fast4x/RiMusic/tree/master/customVersion
> 
> I installed it. I no longer have the problem with the playback buttons.  But it still happens when I use the carousel 

Did you clean install? Create backup, uninstall and then reinstall the app

**Comment by RevanthSurapaneni** [comment]
> > > install this and see if you are still having this problem
> > > https://github.com/fast4x/RiMusic/tree/master/customVersion
> > 
> > 
> > I installed it. I no longer have the problem with the playback buttons.  But it still happens when I use the carousel
> 
> Did you clean install? Create backup, uninstall and then reinstall the app

😁 works! But there is still the problem of unintentional fade in mentioned in another issue... I think fast4x into it.. anyway that's for the quick fix. By the way when a new update drops can I just update it over the custom version or do I have to clean install?

**Comment by aneesh1122** [comment]
> > > > install this and see if you are still having this problem
> > > > https://github.com/fast4x/RiMusic/tree/master/customVersion
> > > 
> > > 
> > > I installed it. I no longer have the problem with the playback buttons.  But it still happens when I use the carousel
> > 
> > Did you clean install? Create backup, uninstall and then reinstall the app
> 
> 😁 works! But there is still the problem of unintentional fade in mentioned in another issue... I think fast4x into it.. anyway that's for the quick fix. By the way when a new update drops can I just update it over the custom version or do I have to clean install?

When new things are added it's always a good practice to clean install otherwise you may face problems like you did now.

**Comment by ALMIGHTY-VC** [comment]
> > > > > install this and see if you are still having this problem
> > > > > https://github.com/fast4x/RiMusic/tree/master/customVersion
> > > > 
> > > > 
> > > > I installed it. I no longer have the problem with the playback buttons.  But it still happens when I use the carousel
> > > 
> > > 
> > > Did you clean install? Create backup, uninstall and then reinstall the app
> > 
> > 
> > 😁 works! But there is still the problem of unintentional fade in mentioned in another issue... I think fast4x into it.. anyway that's for the quick fix. By the way when a new update drops can I just update it over the custom version or do I have to clean install?
> 
> When new things are added it's always a good practice to clean install otherwise you may face problems like you did now.

Bhery bhery fresh install needed ✨but for me the encrypted cache restes in peace

**Comment by RevanthSurapaneni** [comment]
Hey I think I found the cause of the issue. I was going through settings to get my ui the way I like it again, but after that the issue with the carousel happened again! But when I toggled this setting to off, it stopped. I think swiping  through carousel counts as clicking on a new song? 
![Screenshot_20240729_111605](https://github.com/user-attachments/assets/f36aa7ba-9979-43be-9250-b0571d044948)

**Comment by aneesh1122** [comment]
> Hey I think I found the cause of the issue. I was going through settings to get my ui the way I like it again, but after that the issue with the carousel happened again! But when I toggled this setting to off, it stopped. I think swiping through carousel counts as clicking on a new song? ![Screenshot_20240729_111605](https://private-user-images.githubusercontent.com/176787773/353148400-f36aa7ba-9979-43be-9250-b0571d044948.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzA0MjUsIm5iZiI6MTcyMjI3MDEyNSwicGF0aCI6Ii8xNzY3ODc3NzMvMzUzMTQ4NDAwLWYzNmFhN2JhLTk5NzktNDNiZS05MjUwLWIwNTcxZDA0NDk0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNjIyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGRiMmI2NzhiMzhmODBmN2UwMjJmOTBhYjUxNTFkYjJhMGZiNjU0YzEwNjdhYTBkNmYyY2ZlNjVhZDA0N2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MZffZ8Q1s7b65CyG_1fP9IYs0MYEFrFIh7v0hXv-_Zo)

yeah that's the problem. Nice find. I've coded this carousel in such a way that if you change the page the song will be changed too. I'll try to ignore the effect of this option when the carousel is active.
