### ISSUE TITLE
Notification: album and artist are attached ( no space )

### ISSUE THREAD

**Issue by misterhackerman** [fast4x/RiMusic#3285]
### Steps to reproduce the bug

Start any song and look at the notification.

### Expected behavior

Notification content:
Song_name
Artist | Album 

### Actual behavior

Notification content:
Song_name
ArtistAlbum << there should be a space.

### Screenshots/Screen recordings

![Screenshot_2024-08-16-15-29-40-809_org cromite cromite](https://github.com/user-attachments/assets/c1e80eaf-f273-4aa8-93b8-03a17c7ed1eb)

### RiMusic version

0.6.47.1

### Android version

Android 13

**Comment by misterhackerman** [comment]
A pipe "|" would be more appropriate than a space

**Comment by fast4x** [comment]
Fixed, available from version 0.6.48

**Comment by misterhackerman** [comment]
![Screenshot_2024-08-18-13-23-37-601_it.fast4x.rimusic.png](https://github.com/user-attachments/assets/ede3db2b-ab00-4fba-95de-e5488a4328ed)

Still present in 6.48

**Comment by misterhackerman** [comment]
opened new issue #3851 as this was closed but the bug not fixed
