### ISSUE TITLE
App is getting fully closed along with the playing song On pressing Back Button from Home Page

### ISSUE THREAD

**Issue by tiwna16** [fast4x/RiMusic#4239]
### Version of RiMusic

0.6.58.1

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on a Song
3. Click on Back Button from Home Page
4. The App along with the song is getting fully closed.

### Submit a video

https://github.com/user-attachments/assets/cff8834e-1d29-49bd-bc73-b169ee4d2dc0

### What was your expectation?

If I only press back button from Home Page then The App's Exit System should work not forcefully Closed all background functions.

### What more can you tell us? (Optional)

You can clearly see the issue in the video.It's not only happening with only Home Page Songs. Wherever i am going to play the song,If I came back to homepage & press the back button twice,the app gets closed along with the song.

**Comment by RahulRoy13** [comment]
Go to settings 
Then 1st option is user interface
Scroll down
Under the player section there is an option called "close app with back button"

Disable it

**Comment by tiwna16** [comment]
> Go to settings Then 1st option is user interface Scroll down Under the player section there is an option called "close app with back button"
> 
> Disable it

I did bro.
Still the problem persist.That's why I reported about it as bug.Because It wasn't happening before 0.6.58.

**Comment by tiwna16** [comment]
The Problem doesn't get solved in current latest version also.

**Comment by fast4x** [comment]
Disable close with back button in ui settings please

**Comment by sandy2802** [comment]
not working even after disabling. tried uninstalling and did a fresh install. still not working.

**Comment by tiwna16** [comment]
> not working even after disabling. tried uninstalling and did a fresh install. still not working.

True same issue happening & I am reporting about this bug again & again.
