### ISSUE TITLE
Back navigation gesture is not working

### ISSUE THREAD

**Issue by Jit-Halder** [fast4x/RiMusic#4271]
### Version of RiMusic

0.6.58.1

### Android version

14.0

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Open RiMusic
2. Click on A 
3. Click on B
4. Boom! Crash happens

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

https://github.com/user-attachments/assets/87f64e82-09e1-4f34-b73c-2b57b854d566

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

After using back gesture it should go back to the previous page

### What more can you tell us? (Optional)

Whenever I open an album or artist page it does not let me go back to the previous page using the Android back gesture. I have to resort to using the back button of the rimusic app located on the top left which makes the gesture navigation useless.

**Comment by knighthat** [comment]
I'm looking into this now, thanks for reporting

**Comment by knighthat** [comment]
Android be like

> We're on the same version but we're not the same, LOL

https://github.com/user-attachments/assets/106e9aed-a655-484b-a44e-2c196738717d

Anyways, I'll continue to look into this but it is harder to fix since I can't confirm the problem is solved or not

**Comment by Jit-Halder** [comment]
This issue was not present on v0.6.56.1 there the back navigation was working normally but it started happening ever since v0.6.57 was released and is still present in the current latest version v0.6.58.1 . I tried uninstalling and reinstalling the app but the issue still persists.

**Comment by Jit-Halder** [comment]
@knighthat This issue was not present on v0.6.56.1 there the back navigation was working normally but it started happening ever since v0.6.57 was released and is still present in the current latest version v0.6.58.1 . I tried uninstalling and reinstalling the app but the issue still  persists.

**Comment by knighthat** [comment]
This bug was introduced after #4029. 

The problem is that it wasn't there on my test devices, including multiple devices running Android 5 to 14 (physical and virtual).

I'll probably have to look for another the way to trigger the bug, otherwise, I'm not be able to fix it

**Comment by Jit-Halder** [comment]
@knighthat I should also mention that the button navigation of Android works normally it's just the gesture navigation that's causing the issue. Also I'm using a OnePlus device if that helps you in any way.

**Comment by knighthat** [comment]
Now that's even  weirder. Those  actions should behave similarly. Have you tried updating your phone?

**Comment by Jit-Halder** [comment]
Yes it's updated with the latest version. This issue occurs only with this app specifically no other app on my phone is causing this issue.
