### ISSUE TITLE
Problem downloading songs 

### ISSUE THREAD

**Issue by Jhonsilva953** [fast4x/RiMusic#4745]
### Version of RiMusic

0.6.62

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

Simply half of my songs are no longer downloaded, and when I try to download the application it closes and the system says that the application has an error.

### Submit a video

https://github.com/user-attachments/assets/8ba80159-5589-4d2d-901f-18e1e3b0e58e

### What was your expectation?

I wish it would happen this week, I'm really addicted to this app and I can't live without it.

**Comment by fast4x** [comment]
Fixed, available from version 0.6.62.1

**Comment by Jhonsilva953** [comment]
For me the problem is still present

Em dom., 1 de dez. de 2024, 14:13, Rino Russo ***@***.***>
escreveu:

**Comment by fast4x** [comment]
So you your problem is another, send crash log
