### ISSUE TITLE
No me deja escuchar musica dice la fuente del vídeo original de esta canción a sido eliminada

### ISSUE THREAD

**Issue by Gabo248** [fast4x/RiMusic#5025]
### Version of RiMusic

0.6.62.2

### Android version

14

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

No deja escuchar musica 

### Submit a video

If you are on Android, please download a screen recorder and record your screen while you
duplicating the problem as describe above.

> You may need to use Github App to be able to upload video - size limit is 10 MB.

If you are on Desktop, drag video into this box and it will be uploaded automatically

### What was your expectation?

Que arreglen la aplicación

**Comment by fast4x** [comment]
Fixed available from version 0.6.65.1

**Comment by Chulco** [comment]
Still not working, even with 65.1 , some songs do play but the majority don't
