### ISSUE TITLE
Canciones = No ítem found

### ISSUE THREAD

**Issue by Willy2222** [fast4x/RiMusic#5213]
### Version of RiMusic

0.6.66

### Android version

13

### I've done these:

- [X] Uninstall old build before installing a new one
- [X] Checked opening issues about my similar problem

### Tell us how you trigger this bug

1. Abra RiMusic
2. Haga clic en Artista 
3. Haga clic en canciones
4. Sale No ítem Found

### Submit a video

No video

### What was your expectation?

Que se muestre las canciones del artista. 

### What more can you tell us? (Optional)

Nada

### Logs (Optional)

Nada

**Comment by Chandramauli-Arm64** [comment]
**Can you elaborate on it further**? 😀

**Comment by fast4x** [comment]
fixed

**Comment by djshivasttv** [comment]
Unfortunately this is not fixed for me. If I Go on an artist page, then i click the Songs tab i have nothing except "No Items Fond"

This is hapening only with the 0.66.6 on two different device (tablet and phone) and not running the same android version (13 tablet and 14 phone)

**Comment by fast4x** [comment]
fixed, in next version

**Comment by Willy2222** [comment]
> fixed, in next version

Gracias, fast4x, admiro y reconozco su trabajo y dedicación.
Me gusta mucho la aplicación. 
Saludo cordial.
