### ISSUE TITLE
Wrong color for the "go at the top" button

### ISSUE THREAD

**Issue by OrangeZXZ** [fast4x/RiMusic#807]
### Description

![SmartSelect_20240222_072308](https://github.com/fast4x/RiMusic/assets/104271365/a8c9a7f3-02f2-49c9-ae44-5e9bb64e08e9)

### Suggested Solution

The button should be the same color as the bottom bar to be visible

**Comment by fast4x** [comment]
Just fixed in version 0.6.23

**Comment by OrangeZXZ** [comment]
> Just fixed in version 0.6.23

![SmartSelect_20240224_012317.jpg](https://github.com/fast4x/RiMusic/assets/104271365/b3cb0078-05f2-4dd1-b285-1db3a7604d35)

the button is not fixed

**Comment by fast4x** [comment]
Color of repeat button depend by status on/off

**Comment by OrangeZXZ** [comment]
> Color of repeat button depend by status on/off

i was talking about the up arrow button that is invisible sorry for not being more precisely

**Comment by fast4x** [comment]
Ahhhhhhhh ok ok

**Comment by fast4x** [comment]
Improved, available from version 0.6.24
